import json, random

# Huge landscape continent matched to the painted realm (bg_map.png ~16:9). Big enough that
# tiles are small and you zoom in (PanZoom) to select them. Player starts in a CORNER so
# there's a long conquest runway and difficulty rises as you push across the continent.
W, H = 120, 68          # 2x the old 60x34 (4x the tiles), same landscape ratio
SEED = 20260714
N_AI = 50
random.seed(SEED)

# --- value-noise landmass with edge falloff (organic continent + a sea margin) ---
gw, gh = W // 4 + 2, H // 4 + 2
grid = [[random.random() for _ in range(gw)] for _ in range(gh)]
def smooth(gx, gy):
    x0, y0 = int(gx), int(gy); fx, fy = gx - x0, gy - y0
    x1, y1 = min(x0 + 1, gw - 1), min(y0 + 1, gh - 1)
    a = grid[y0][x0]*(1-fx)+grid[y0][x1]*fx
    b = grid[y1][x0]*(1-fx)+grid[y1][x1]*fx
    return a*(1-fy)+b*fy

rows = []
for y in range(H):
    row = ""
    for x in range(W):
        n = smooth(x/4, y/4)
        dx = (x-(W-1)/2)/((W-1)/2); dy = (y-(H-1)/2)/((H-1)/2)
        fall = (dx*dx*0.96 + dy*dy*1.06) ** 0.5
        row += "#" if ((1 - fall) + n*0.33) > 0.36 else "."
    rows.append(row)

land = [(x, y) for y in range(H) for x in range(W) if rows[y][x] == "#"]
def cheb(a, b): return max(abs(a[0]-b[0]), abs(a[1]-b[1]))

# Player in the SW corner of the continent (nearest land to grid corner (0, H-1)), inset a
# little so the capital has neighbours.
player = min(land, key=lambda t: t[0] + (H - 1 - t[1]))

# Farthest-point scatter for the rivals (spreads them across the whole continent).
chosen = [player]
for _ in range(N_AI):
    best, bestd = None, -1
    for t in land:
        if t in chosen: continue
        d = min(cheb(t, c) for c in chosen)
        if d > bestd: best, bestd = t, d
    chosen.append(best)
ai_tiles = chosen[1:]

# Deterministic medieval-ish name pool (prefix + suffix), enough for many rivals.
PRE = ["Ash","Black","Brook","Dun","East","Fair","Grey","High","Iron","Nor","Oak","Red",
       "Stone","Storm","West","Win","Wolf","Yew","Frost","Raven","Gold","Thorn","Dusk",
       "Bram","Hart","Marsh","Cold","Far","Holm","Bel","Crow","Elder","Hawk","Mor"]
SUF = ["mere","cliff","dale","fell","fen","ford","gate","hollow","holm","moor","port",
       "stead","thorpe","ton","vale","wick","worth","hold","fort","watch","haven","shaw",
       "bourne","crag","reach","march"]
pool = [p + s for p in PRE for s in SUF]
random.shuffle(pool)
names = []
seen = set()
for nm in pool:
    if nm.lower() not in seen:
        names.append(nm); seen.add(nm.lower())
    if len(names) >= N_AI: break

dists = sorted(cheb(player, t) for t in ai_tiles)
def diff_for(t):
    d = cheb(player, t); q = sum(1 for x in dists if x < d) / max(1, len(dists))
    return 1 + min(4, int(q * 5))
def garrison(diff):
    g = [{"troop":"spearman","count":4+diff*5},{"troop":"archer","count":3+diff*4}]
    if diff>=2: g.append({"troop":"swordsman","count":diff*3})
    if diff>=3: g.append({"troop":"horseman","count":2+diff*2})
    if diff>=4: g.append({"troop":"knight","count":diff})
    if diff>=5: g.append({"troop":"man_at_arms","count":diff*2})
    return g
def forts(diff):
    f = [{"building":"wall","level":min(diff,4)}]
    if diff>=2: f.append({"building":"tower","level":min(diff-1,4)})
    if diff>=4: f.append({"building":"watchtower","level":min(diff-3,3)})
    return f
def loot(diff): return {"food":80*diff,"wood":90*diff,"stone":70*diff,"iron":25*diff,"gold":40*diff}

ai = []
for i, t in enumerate(ai_tiles):
    diff = diff_for(t)
    nm = names[i] if i < len(names) else f"Holdfast {i}"
    ai.append({"id": f"ai_{nm.lower()}", "name": nm, "tile": {"x": t[0], "y": t[1]},
        "difficulty": diff, "loot": loot(diff), "garrison": garrison(diff),
        "fortifications": forts(diff), "regrowTicks": 720 + diff * 420})

world = {"$comment": "Huge procedural landscape continent ('#' land, '.' sea), aligned to the painted realm map. Player starts in the SW corner. Generated by tools/genworld.py.",
    "gridSize": {"w": W, "h": H}, "land": rows, "player": {"tile": {"x": player[0], "y": player[1]}}, "aiVillages": ai}
open("content/world.json", "w").write(json.dumps(world, indent=2))
print("size", W, "x", H, "land", len(land), "factions", len(ai), "player", player)
