import json, random

W, H = 60, 34           # landscape map to match the painted realm (≈16:9)
SEED = 20260622
random.seed(SEED)

# --- value-noise landmass with edge falloff (organic continent + a sea margin) ---
gw, gh = W // 4 + 2, H // 4 + 2
grid = [[random.random() for _ in range(gw)] for _ in range(gh)]
def smooth(gx, gy):
    x0, y0 = int(gx), int(gy); fx, fy = gx - x0, gy - y0
    x1, y1 = min(x0 + 1, gw - 1), min(y0 + 1, gh - 1)
    a = grid[y0][x0]*(1-fx)+grid[y0][x1]*fx
    b = grid[y1][x0]*(1-fx)+grid[y1][x1]*fx
    return a*(1-fy)+b*fy

rows = []
for y in range(H):
    row = ""
    for x in range(W):
        n = smooth(x/4, y/4)
        # elliptical falloff: a SOLID continent core with an organic coast, filling most of
        # the frame (the painted continent fills ~85%), leaving only a thin sea margin.
        dx = (x-(W-1)/2)/((W-1)/2); dy = (y-(H-1)/2)/((H-1)/2)
        fall = (dx*dx*0.96 + dy*dy*1.06) ** 0.5
        row += "#" if ((1 - fall) + n*0.33) > 0.36 else "."
    rows.append(row)

land = [(x, y) for y in range(H) for x in range(W) if rows[y][x] == "#"]
def cheb(a, b): return max(abs(a[0]-b[0]), abs(a[1]-b[1]))

player = min(land, key=lambda t: abs(t[0]-W//2) + abs(t[1]-H//2))
chosen = [player]
N_AI = 20
for _ in range(N_AI):
    best, bestd = None, -1
    for t in land:
        if t in chosen: continue
        d = min(cheb(t, c) for c in chosen)
        if d > bestd: best, bestd = t, d
    chosen.append(best)
ai_tiles = chosen[1:]

names = ["Brookmere","Southport","Dunhollow","Eastmarch","Greyfen","Highfort","Westvale",
         "Ironcliff","Stormhold","Ravenmoor","Blackmoor","Oakshield","Frostholm","Thornwood",
         "Redhaven","Goldmere","Wolfden","Duskmere","Ashford","Karrock"]

dists = sorted(cheb(player,t) for t in ai_tiles)
def diff_for(t):
    d = cheb(player,t); q = sum(1 for x in dists if x < d)/max(1,len(dists))
    return 1+min(4,int(q*5))
def garrison(diff):
    g=[{"troop":"spearman","count":4+diff*5},{"troop":"archer","count":3+diff*4}]
    if diff>=2: g.append({"troop":"swordsman","count":diff*3})
    if diff>=3: g.append({"troop":"horseman","count":2+diff*2})
    if diff>=4: g.append({"troop":"knight","count":diff})
    if diff>=5: g.append({"troop":"man_at_arms","count":diff*2})
    return g
def forts(diff):
    f=[{"building":"wall","level":min(diff,4)}]
    if diff>=2: f.append({"building":"tower","level":min(diff-1,4)})
    if diff>=4: f.append({"building":"watchtower","level":min(diff-3,3)})
    return f
def loot(diff): return {"food":80*diff,"wood":90*diff,"stone":70*diff,"iron":25*diff,"gold":40*diff}

ai=[]
for i,t in enumerate(ai_tiles):
    diff=diff_for(t)
    ai.append({"id":f"ai_{names[i].lower()}","name":names[i],"tile":{"x":t[0],"y":t[1]},
        "difficulty":diff,"loot":loot(diff),"garrison":garrison(diff),
        "fortifications":forts(diff),"regrowTicks":720+diff*420})

world={"$comment":"Procedural landscape continent ('#' land, '.' sea), aligned to the painted realm map. Generated by tools/genworld.py.",
    "gridSize":{"w":W,"h":H},"land":rows,"player":{"tile":{"x":player[0],"y":player[1]}},"aiVillages":ai}
open("content/world.json","w").write(json.dumps(world,indent=2))
print("size",W,"x",H,"land",len(land),"factions",len(ai),"player",player)
print()
mark={(player[0],player[1]):"@"}
for i,t in enumerate(ai_tiles): mark[t]="o"
for y in range(H):
    print("".join(mark.get((x,y), rows[y][x]) for x in range(W)))
